# Generated by Django 4.0 on 2021-12-21 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("dbsettings", "0003_alter_root_id_for_django20"),
    ]

    operations = [
        migrations.CreateModel(
            name="Settings",
            fields=[
                (
                    "root",
                    models.OneToOneField(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        primary_key=True,
                        related_name="%(app_label)s_%(class)s",
                        serialize=False,
                        to="dbsettings.root",
                    ),
                ),
                ("test_char", models.CharField(default="foo", max_length=25)),
                ("test_bool_true", models.BooleanField(default=True)),
                ("test_bool_false", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
