# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-03 16:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbsettings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='root',
            options={'verbose_name': 'settings', 'verbose_name_plural': 'settings'},
        ),
    ]
