# Generated by Django 4.0 on 2021-12-21 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dbsettings", "0002_auto_20161121_0213"),
    ]

    operations = [
        migrations.AlterField(
            model_name="root",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
